server:
    port:8080
spring:
  jpa:
    hibernate:
      ddl-auto: create
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    url: "jdbc:postgresql://postgres.lb-probe.svc.local:5432/postgresdb"
    username: admin
    password: admin
