kind: Service
apiVersion: v1
metadata:
  name: "e-payment-service"
  namespace: default
spec:
  type: ClusterIP
  selector:
    app: e-payment
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
